# Site settings
title: closeup.js
email: shane.osbourne8@gmail.com
description: "A modern, minimalist image zoomer."
baseurl: ""
url: "http://shakyshane.github.io/closeup.js/"
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json", "bower_components"]

# Build settings
markdown: kramdown
permalink: pretty
